AWSTemplateFormatVersion: 2010-09-09

Description: |
  The following CloudFormation CockroachLabs Cloud resource type allows the creation and configuration of 
  a CockroachDB serverless cluster with databases and SQL users, and outputs some of the information needed
  to connect to the database.
      
Resources:
  CockroachCluster:
    Type: CockroachLabs::ServerlessCluster::CockroachDB
    Properties:
      Name: demo-cluster
      Provider: AWS
      Regions:
        - us-east-1
      SpendLimit: 0
      Databases:
        - Name: Demo-CockroachDB
        - Name: Another_CRDB
      Users:
        - Name: superuser
          Password: supersecret1
        - Name: editor
          Password: abcdefghijkl
        - Name: reader
          Password: mypwd%$#@987

Outputs:
  SQLDNS:
    Description: SQL DNS is used to connect to the database - postgresql://<SQL-USERNAME>:<SQL-PASSWORD>@<SQL-DNS>:26257/<DB-NAME>?sslmode=verify-full
    Value: !GetAtt CockroachCluster.SqlDns
  Certificate:
    Description: CA Certificate to access SQL databases
    Value: !GetAtt CockroachCluster.Certificate